server.port=8080

spring.application.name=architecture-zuul
eureka.client.serviceUrl.defaultZone=http://demo-microservice-eureka:9999/eureka/
# eureka\u5B9E\u4F8B\u9762\u677F\u663E\u793A\u7684\u5B9E\u4F8B\u6807\u8BC6
eureka.instance.instance-id=${spring.application.name}
# eureka\u5B9E\u4F8B\u9762\u677F\u663E\u793A\u5B9E\u4F8B\u7684\u4E3B\u673Aip
eureka.instance.prefer-ip-address=true

zuul.routes.api-a.path=/api/v1/**
zuul.routes.api-a.service-id=architecture-helloworld
zuul.routes.api-a.strip-prefix=false

# \u591A\u4E2Aurl\u7528\u9017\u53F7\u9694\u5F00
zuul.ignored-patterns=/api/v1/zuul/test1,/api/v1/zuul/test2

logging.level.root=info

# https://www.appsdeveloperblog.com/pass-authorization-header-to-downstream-microservice/
# \u8BBE\u7F6ECookie\u548CSet-Cookie\u4E3A\u654F\u611F\u5934\uFF0CAuthorization\u4E0D\u662F\uFF0C\u6240\u4EE5Authorization\u88AB\u4F20\u9012\u5230\u4E0B\u6E38
zuul.sensitiveHeaders=Cookie,Set-Cookie

ribbon.ReadTimeout=8000
ribbon.ConnectTimeout=8000
ribbon.MaxAutoRetries=0
ribbon.MaxAutoRetriesNextServer=0
ribbon.MaxConnectionsPerHost=100
ribbon.MaxTotalConnections=400

# \u8BBE\u7F6Ezuul route hystrix
feign.hystrix.enabled=true
hystrix.command.default.fallback.enabled=true
hystrix.command.default.execution.timeout.enabled=true
hystrix.command.default.execution.isolation.strategy=THREAD
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=10000
hystrix.threadpool.default.maxQueueSize=50
hystrix.threadpool.default.queueSizeRejectionThreshold=50
hystrix.threadpool.default.allowMaximumSizeToDivergeFromCoreSize=true
hystrix.command.default.circuitBreaker.enabled=true
zuul.ribbonIsolationStrategy=THREAD
zuul.threadPool.useSeparateThreadPools=true
