version: "3.0"

# 创建网络
networks:
  net:
    name: demo-elk-elasticsearch

services:
  demo-elk-elasticsearch:
    container_name: demo-elk-elasticsearch
    image: docker.118899.net:10001/demo-elk-elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - discovery.type=single-node
      # http.cors表示允许elasticsearch-head连接并管理
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - TZ=Asia/Shanghai
    ports:
      - 9200:9200
      # Java transport client需要连接这个端口去操作elasticsearch
      - 9300:9300
    volumes:
      - ~/data-demo-elk-elasticsearch:/usr/share/elasticsearch/data
    networks:
      - net

  demo-elk-elasticsearch-head:
    container_name: demo-elk-elasticsearch-head
    image: docker.118899.net:10001/demo-elk-elasticsearch-head
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 9100:9100
    networks:
      - net