FROM 192.168.235.138:80/library/demo-openresty-base-dev

# # 测试resty.limit.req
# COPY nginx-lua-resty-limit-req.conf /usr/local/openresty/nginx/conf/nginx.conf

# 测试resty.limit.count
# COPY nginx-lua-resty-limit-count.conf /usr/local/openresty/nginx/conf/nginx.conf

# 测试resty.limit.conn
# COPY nginx-lua-resty-limit-conn.conf /usr/local/openresty/nginx/conf/nginx.conf

# 测试resty.limit.traffic
# COPY nginx-lua-resty-limit-traffic.conf /usr/local/openresty/nginx/conf/nginx.conf

# 测试限制组合
COPY nginx-lua-resty-limit-combine.conf /usr/local/openresty/nginx/conf/nginx.conf
