version: "3.0"

# 创建网络
networks:
  net:
    name: demo-mariadb-standalone-net

services:
  # docker 运行 centos/mariadb
  # https://hub.docker.com/r/centos/mariadb
  # 使用指定字符集启动mariadb
  # https://stackoverflow.com/questions/45729326/how-to-change-the-default-character-set-of-mysql-using-docker-compose/53629912
  
  # 挂载数据库初始化脚本db.sql
  # NOTE: db.sql脚本挂载前已存，否则映射到容器的db.sql为目录类型，宿主机的db.sql需要chmod a+r db.sql赋予r权限，否则容器启动过程中会失败并且提示permission denied。
  # docker run --rm --name mariadb-demo -p 3306:3306 -v /data/data-mariadb-demo:/var/lib/mysql -v $(pwd)/db.sql:/docker-entrypoint-initdb.d/db.sql -e MYSQL_ROOT_PASSWORD=123456 -e TZ=Asia/Shanghai mariadb:10.4.19  --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --skip-character-set-client-handshake
  demo-mariadb-standalone-server:
    container_name: demo-mariadb-standalone-server
    image: mariadb:10.4.19
    command:
     - --character-set-server=utf8mb4
     - --collation-server=utf8mb4_general_ci
     - --skip-character-set-client-handshake
    #volumes:
    #  - ~/data-demo-mariadb-standalone-server:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
    networks:
      - net

