server.port=8080
spring.application.name=spring-boot-autoconfiguration

logging.level.com.future.demo=debug

com.future.demo.test.prop1=astring1
com.future.demo.test.prop2=18080
com.future.demo.test.prop3[0]=av1
com.future.demo.test.prop3[1]=av2
com.future.demo.test.prop4.k1=avv1
com.future.demo.test.prop4.k2=avv2
com.future.demo.test.nested.prop1=anv1
com.future.demo.test.nested.prop2=18090