server.port=8080

spring.application.name=demo-springcloud-zuul
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# eureka注册中心注册地址
eureka.client.serviceUrl.defaultZone=http://abc1.com:9999/eureka/,http://abc2.com:10000/eureka/,http://abc3.com:10001/eureka/
# eureka实例面板显示的实例标识
eureka.instance.instance-id=zuul1
# eureka实例面板显示实例的主机ip
eureka.instance.prefer-ip-address=true

# 客户端向注册中心发送心跳的时间间隔，（默认30秒）
eureka.instance.lease-renewal-interval-in-seconds=5
# eureka注册中心（服务端）在收到客户端心跳之后，等待下一次心跳的超时时间，如果在这个时间内没有收到下次心跳，则移除该客户端。（默认90秒）
eureka.instance.lease-expiration-duration-in-seconds=15

zuul.routes.api-a.path=/api/v1/**
zuul.routes.api-a.service-id=demo-springcloud-helloworld
zuul.routes.api-a.strip-prefix=false

# 多个url用逗号隔开
zuul.ignored-patterns=/api/v1/zuul/test1,/api/v1/zuul/test2

logging.level.root=info