server.port=8080
spring.application.name=spring-security-user-and-password-datasource

## 使用配置文件配置用户密码
## 对应SecurityProperties配置类
## 注意: 不需要配置WebSecurityConfigurerAdapter和配置PasswordEncoder(否则登录时报错)
#spring.security.user.name=user1
#spring.security.user.password=123456
#spring.security.user.roles=role1