version: "3.0"

# 创建网络
networks:
  net:
    name: demo-redis-server-net

services:
  # 启动redis
  demo-redis-server:
    container_name: demo-redis-server
    image: redis:5.0.14
    # 设置redis密码
    command: redis-server --requirepass 123456
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6379:6379
    networks:
      - net

