FROM registry.cn-hangzhou.aliyuncs.com/future-public/openresty-base:1.1.1

RUN rm -rf /usr/local/openresty/nginx/html/*

#COPY dist/* /usr/local/openresty/nginx/html/
COPY dist/ /usr/local/openresty/nginx/html/
