server.port=9001

spring.profiles.active=dev

spring.application.name=service-level-first-provider
eureka.client.serviceUrl.defaultZone=http://${eurekaServer:localhost}:9999/eureka/
spring.application.logstash.server=${logstashServer}