## Configuring info endpoint
info.app.name=Spring Sample Application
info.app.description=This is my first spring boot application
info.app.version=1.0.0
info.java-vendor = ${java.specification.vendor}
info.customize.info1=Information 1
info.customize.info2=Information 2

# \u6307\u5B9Aactuator\u7AEF\u53E3
management.server.port=8081
management.endpoints.web.exposure.include=*