version: "3.0"

services:
  demo-elk-elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile-elasticsearch
    image: registry.cn-hangzhou.aliyuncs.com/future-public/demo-elk-elasticsearch-es9
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - TZ=Asia/Shanghai
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - 9200:9200
      - 9300:9300

  demo-elk-kibana:
    image: docker.elastic.co/kibana/kibana:9.0.0
    environment:
      ELASTICSEARCH_HOSTS: http://demo-elk-elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - demo-elk-elasticsearch

  demo-elk-logstash:
    build:
      context: .
      dockerfile: Dockerfile-logstash
    image: registry.cn-hangzhou.aliyuncs.com/future-public/demo-elk-logstash-es9
    environment:
      - xpack.monitoring.elasticsearch.hosts=[ "http://demo-elk-elasticsearch:9200" ]
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044

  # 定时删除过期索引
  demo-elk-curator:
    build:
      context: .
      dockerfile: Dockerfile-curator
    image: registry.cn-hangzhou.aliyuncs.com/future-public/demo-elk-curator-es9
    volumes:
      - ./curator.yml:/.curator/curator.yml
      - ./action.yml:/.curator/action.yml
    entrypoint: /bin/sh
    command: -c "while true; do /curator/curator --config /.curator/curator.yml /.curator/action.yml; sleep 10; done;"
