spring.application.name=demo-spring-boot-admin-server
server.port=8082

# SpringBoot Admin \u5B89\u5168\u9632\u62A4\u7684 Spring Security \u914D\u7F6E
spring.security.user.name=root
spring.security.user.password=123456
