version: "3.0"

networks:
  net:
    external: true
    name: demo-redis-server-cluster-net

services:
  demo-redis-cluster-node-extra:
    container_name: demo-redis-cluster-node-extra
    image: my-redis-cluster:5.0.14
    command: redis-server /usr/local/etc/redis/redis.conf --port 6390 --cluster-announce-ip ${varHostIp}
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./redis.cluster.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6390:6390
      - 16390:16390
    networks:
      - net
  demo-redis-cluster-node-extra-slave:
    container_name: demo-redis-cluster-node-extra-slave
    image: my-redis-cluster:5.0.14
    command: redis-server /usr/local/etc/redis/redis.conf --port 6391 --cluster-announce-ip ${varHostIp}
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./redis.cluster.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6391:6391
      - 16391:16391
    networks:
      - net
  
