version: "3.0"

services:
  demo-redis-cluster-node1:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: my-redis-cluster:5.0.14
    # 必须设置cluster-announce-ip才能够在创建集群时节点join到master，否则会一直waiting...
    command: redis-server /usr/local/etc/redis/redis.conf --port 6380 --cluster-announce-ip 127.0.0.1
    volumes:
      - ./redis.cluster.conf:/usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    # ports:
    #   - 6380:6380
    #   # 必须映射cluster-announce-bus-port才能够在创建集群时节点join到master，否则会一直waiting...
    #   - 16380:16380
    # networks:
    #   - net
    network_mode: 'host'

  demo-redis-cluster-node2:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: my-redis-cluster:5.0.14
    command: redis-server /usr/local/etc/redis/redis.conf --port 6381 --cluster-announce-ip 127.0.0.1
    volumes:
      - ./redis.cluster.conf:/usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    network_mode: 'host'

  demo-redis-cluster-node3:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: my-redis-cluster:5.0.14
    command: redis-server /usr/local/etc/redis/redis.conf --port 6382 --cluster-announce-ip 127.0.0.1
    volumes:
      - ./redis.cluster.conf:/usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    network_mode: 'host'

  demo-redis-cluster-node4:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: my-redis-cluster:5.0.14
    command: redis-server /usr/local/etc/redis/redis.conf --port 6383 --cluster-announce-ip 127.0.0.1
    volumes:
      - ./redis.cluster.conf:/usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    network_mode: 'host'

  demo-redis-cluster-node5:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: my-redis-cluster:5.0.14
    command: redis-server /usr/local/etc/redis/redis.conf --port 6384 --cluster-announce-ip 127.0.0.1
    volumes:
      - ./redis.cluster.conf:/usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    network_mode: 'host'

  demo-redis-cluster-node6:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: my-redis-cluster:5.0.14
    command: redis-server /usr/local/etc/redis/redis.conf --port 6385 --cluster-announce-ip 127.0.0.1
    volumes:
      - ./redis.cluster.conf:/usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    network_mode: 'host'

  redis-cluster-creator:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: redis-cluster-creator
    image: my-redis-cluster:5.0.14
    entrypoint: [/bin/sh, -c, 'echo "yes" | redis-cli --cluster create --cluster-replicas 1 127.0.0.1:6380 127.0.0.1:6381 127.0.0.1:6382 127.0.0.1:6383 127.0.0.1:6384 127.0.0.1:6385']
    depends_on:
      - demo-redis-cluster-node1
      - demo-redis-cluster-node2
      - demo-redis-cluster-node3
      - demo-redis-cluster-node4
      - demo-redis-cluster-node5
      - demo-redis-cluster-node6
    network_mode: 'host'
