{
 "title": "秒杀应用监控",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "订单总数",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flash_sale_total_count{instance=\"crond-service-1\", job=\"Crond Actuator\", type=\"order\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "商品总数",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flash_sale_total_count{instance=\"crond-service-1\", job=\"Crond Actuator\", type=\"product\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "查询索引总数-根据用户ID查询",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flash_sale_total_count{instance=\"crond-service-1\", job=\"Crond Actuator\", type=\"cassandra-index-orderListByUserId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "查询索引总数-根据商家ID查询",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flash_sale_total_count{instance=\"crond-service-1\", job=\"Crond Actuator\", type=\"cassandra-index-orderListByMerchantId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "秒杀订单同步速度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(irate(flash_sale_order_sync_count_total{job=\"Crond Actuator\",order=\"master\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cassandra索引创建速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 2 },
   "targets": [
    {
     "expr": "sum(irate(flash_sale_cassandra_index_create_total{job=\"Crond Actuator\"}[$__rate_interval])) by (instance,type)",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "计数器指标",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 2 },
   "targets": [
    {
     "expr": "rate(increase_count_stats_total{job=\"Crond Actuator\", type=\"success\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "商品指标",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(product_metrics_total{}[$__rate_interval])) by (instance,type)",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "下单指标",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(purchase_stats_total{job=\"Api Actuator\"}[$__rate_interval])) by (instance,type)",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  }
 ]
}