version: "3.0"

services:
  com-future-demo-business-backend:
    container_name: com-future-demo-business-backend
    image: docker.118899.net:10001/yyd-public/demo-x-forwarded-for-backend:1.0.0
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8080:8080