CREATE DATABASE IF NOT EXISTS demo DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE demo;

-- 用于协助测试垂直分库
CREATE TABLE IF NOT EXISTS `user`(
     id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '用户ID' ,
     create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
     `name` VARCHAR(128) NOT NULL COMMENT '用户名称',
    balance decimal(20,5) not null default 0 comment '用户余额'
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 用于协助演示绑定表关系
CREATE TABLE IF NOT EXISTS product_1 (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '商品ID',
    `name` VARCHAR(512) NOT NULL COMMENT '商品名称',
    create_time DATETIME NOT NULL COMMENT '创建时间'
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS product_description_1 (
   id BIGINT NOT NULL PRIMARY KEY COMMENT '商品描述ID',
   product_id BIGINT NOT NULL COMMENT '商品ID',
   `description` TEXT COMMENT '商品描述'
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS product_2 (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '商品ID',
    `name` VARCHAR(512) NOT NULL COMMENT '商品名称',
    create_time DATETIME NOT NULL COMMENT '创建时间'
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS product_description_2 (
     id BIGINT NOT NULL PRIMARY KEY COMMENT '商品描述ID',
     product_id BIGINT NOT NULL COMMENT '商品ID',
     `description` TEXT COMMENT '商品描述'
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
