FROM demo-k8s-jmeter-base:latest

COPY jmeter-master-tmpl /usr/local/jmeter/bin/jmeter
RUN chmod +x /usr/local/jmeter/bin/jmeter
COPY jmeter.properties /usr/local/jmeter/bin/jmeter.properties
		
EXPOSE 60000
