FROM demo-k8s-jmeter-base:latest

COPY jmeter-slave-tmpl /usr/local/jmeter/bin/jmeter
RUN chmod +x /usr/local/jmeter/bin/jmeter
COPY jmeter.properties /usr/local/jmeter/bin/jmeter.properties

EXPOSE 1099 50000

ENTRYPOINT $JMETER_HOME/bin/jmeter-server \
-Dserver.rmi.localport=50000 \
-Dserver_port=1099 \
-Jserver.rmi.ssl.disable=true