FROM openjdk:8-jdk-slim-bullseye

COPY sources.list /etc/apt/sources.list

RUN apt-get clean && \
    apt-get update && \
    apt-get install -y curl

RUN curl https://fut001.oss-cn-hangzhou.aliyuncs.com/jmeter/apache-jmeter-5.6.2.tgz --output /tmp/apache-jmeter-5.6.2.tgz && \
    cd /tmp && tar -xvzf apache-jmeter-5.6.2.tgz && mv /tmp/apache-jmeter-5.6.2 /usr/local/jmeter && \
    rm -f /tmp/apache-jmeter-5.6.2.tgz

# 复制插件到jmeter lib/ext目录
COPY ./target/demo-jmeter-customize-plugin-1.0.0.jar /usr/local/jmeter/lib/ext/demo-jmeter-customize-plugin-1.0.0.jar
# 复制插件依赖的库到jmeter lib/ext目录，否则会报告ClassNotFound错误
COPY ./target/required-lib/*.jar /usr/local/jmeter/lib/ext/

ENV JMETER_HOME /usr/local/jmeter
		
ENV PATH $JMETER_HOME/bin:$PATH

