server.port=18080

# \u914D\u7F6Emybatis xml\u914D\u7F6E\u6587\u4EF6\u8DEF\u5F84
mybatis.mapper-locations=classpath:mapper/*.xml,classpath:mapper/**/*.xml
# \u542F\u7528\u6570\u636E\u5E93\u5B57\u6BB5\u4E0B\u5212\u7EBF\u5230`bean`\u9A7C\u5CF0\u547D\u540D\u81EA\u52A8\u8F6C\u6362
mybatis.configuration.map-underscore-to-camel-case=true

# \u8F93\u5165SQL\u5230\u65E5\u5FD7\u4E2D
#logging.level.root=debug
logging.level.com.future.demo=info

spring.shardingsphere.datasource.names=ds1
spring.shardingsphere.datasource.ds1.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds1.driver-class-name=org.mariadb.jdbc.Driver
spring.shardingsphere.datasource.ds1.jdbc-url=jdbc:mariadb://localhost:3306/demo?allowMultiQueries=true
spring.shardingsphere.datasource.ds1.username=root
spring.shardingsphere.datasource.ds1.password=123456

# \u6307\u5B9At_order\u8868\u7684\u4E3B\u952E\u751F\u6210\u7B56\u7565\u4E3ASNOWFLAKE
spring.shardingsphere.sharding.tables.order.key-generator.column=id
spring.shardingsphere.sharding.tables.order.key-generator.type=SNOWFLAKE
# \u6307\u5B9Aorder\u8868\u7684\u6570\u636E\u5206\u5E03\u60C5\u51B5\uFF0C\u914D\u7F6E\u6570\u636E\u8282\u70B9
spring.shardingsphere.sharding.tables.order.actual-data-nodes=ds1.order_$->{1..2}
# order\u8868\u7684\u5206\u7247\u7B56\u7565\uFF0C\u5206\u7247\u7B56\u7565\u5305\u62EC\u5206\u7247\u952E\u548C\u5206\u7247\u7B97\u6CD5
spring.shardingsphere.sharding.tables.order.table-strategy.inline.sharding-column=id
spring.shardingsphere.sharding.tables.order.table-strategy.inline.algorithm-expression=order_$->{id % 2 + 1}

# \u6253\u5F00sql\u8F93\u51FA\u65E5\u5FD7
spring.shardingsphere.props.sql.show=true
