logging.level.com.future.demo=debug

#leaf.name=com.sankuai.leaf.opensource.test
#leaf.segment.enable=false
##leaf.segment.url=
##leaf.segment.username=
##leaf.segment.password=

# \u542F\u7528\u96EA\u82B1\u7B97\u6CD5\u751F\u6210\u5206\u5E03\u5F0FID
leaf.snowflake.enable=true
# zookeeper\u5730\u5740
leaf.snowflake.address=127.0.0.1:2181
#leaf.snowflake.port=9999
