server.port=8080
spring.application.name=demo-java-performance

#server.tomcat.max-connections=1

#server.tomcat.accept-count=1

# https://blog.csdn.net/weixin_30396699/article/details/101770028
# The number of milliseconds this Connector will wait, after accepting a connection, for the request URI line to be presented. The default value is 60000 (i.e. 60 seconds).
# 使用telnet 192.168.1.181 8080测试这个参数，telnet后不输入request URI数据，连接会在connectionTimeout后被服务器主动关闭
server.tomcat.connection-timeout=30000

# tomcat最大worker线程数
server.tomcat.max-threads=200

# tomcat空闲时候也需要保持的最小空闲worker线程数
server.tomcat.min-spare-threads=20

# NOTE: 只需要配置minSpareThreads即可，配置了maxSpareThreads经过测试也没有效果
# server.tomcat.max-spare-threads=5
# NOTE: springboot没有提供maxIdleTime配置，在springboot中硬编码为60秒
# 60秒后tomcat会自动回收空闲的线程，使tomcat当前worker线程数等于minSpareThreads值
# server.tomcat.max-idle-time=120000

# 启用tomcat jmx
server.tomcat.mbeanregistry.enabled=true

spring.thymeleaf.cache=false
