version: '3'

# https://docs.locust.io/en/1.5.2/running-locust-docker.html
services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/test_json_parse_perf_client.py --master -H http://master:8089

  worker:
    image: locustio/locust
    deploy:
      # 多少个worker，和cpu数量相等为宜
      replicas: 1
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/test_json_parse_perf_client.py --worker --master-host master
