version: "3.1"

services:
  # Redis Standalone 模式
  redis-standalone:
    image: redis:5.0.14
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass 123456
    volumes:
      - ./redis-standalone.conf:/usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    network_mode: host

  # Redis Replication 模式
  redis-replication-node1:
    build:
      context: .
      dockerfile: ./Dockerfile-replication
    command: redis-server /usr/local/etc/redis/redis.conf --port 6479
    environment:
      - TZ=Asia/Shanghai
    network_mode: host

  redis-replication-node2:
    build:
      context: .
      dockerfile: ./Dockerfile-replication
    command: redis-server /usr/local/etc/redis/redis.conf --port 6480
    environment:
      - TZ=Asia/Shanghai
    network_mode: host
    depends_on:
      - redis-replication-node1
  redis-replication-node2-slave-join:
    build:
      context: .
      dockerfile: ./Dockerfile-replication
    command: sh -c "dockerize -wait tcp://localhost:6479 -timeout 120s -wait-retry-interval 5s
      && dockerize -wait tcp://localhost:6480 -timeout 120s -wait-retry-interval 5s
      && redis-cli -h localhost -p 6480 slaveof localhost 6479
      && redis-cli -h localhost -p 6480 config rewrite
      && echo \"成功join slave\""
    environment:
      - TZ=Asia/Shanghai
    network_mode: host
    depends_on:
      - redis-replication-node1

  redis-replication-node3:
    build:
      context: .
      dockerfile: ./Dockerfile-replication
    command: redis-server /usr/local/etc/redis/redis.conf --port 6481
    environment:
      - TZ=Asia/Shanghai
    network_mode: host
    depends_on:
      - redis-replication-node1
  redis-replication-node3-slave-join:
    build:
      context: .
      dockerfile: ./Dockerfile-replication
    command: sh -c "dockerize -wait tcp://localhost:6479 -timeout 120s -wait-retry-interval 5s
      && dockerize -wait tcp://localhost:6481 -timeout 120s -wait-retry-interval 5s
      && redis-cli -h localhost -p 6481 slaveof localhost 6479
      && redis-cli -h localhost -p 6481 config rewrite
      && echo \"成功join slave\""
    environment:
      - TZ=Asia/Shanghai
    network_mode: host
    depends_on:
      - redis-replication-node1

  # Redis Sentinel 模式
  demo-redis-sentinel-repl-node1:
    build:
      context: .
      dockerfile: ./Dockerfile-sentinel
    command: redis-server /usr/local/etc/redis/redis.conf --port 6579 --replica-announce-ip localhost --replica-announce-port 6579
    environment:
      - TZ=Asia/Shanghai
    

  demo-redis-sentinel-repl-node2:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: demo-redis-sentinel-repl-node2
    image: my-redis:5.0.14
    command: redis-server /usr/local/etc/redis/redis.conf --port 6379 --replica-announce-ip ${varHostIp} --replica-announce-port 6380
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6380:6379
    networks:
      - net
    depends_on:
      - demo-redis-sentinel-repl-node1
  demo-redis-sentinel-repl-node2-slave-join:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: demo-redis-sentinel-repl-node2-slave-join
    image: my-redis:5.0.14
    command: sh -c "dockerize -wait tcp://demo-redis-sentinel-repl-node1:6379 -timeout 120s -wait-retry-interval 5s
      && dockerize -wait tcp://demo-redis-sentinel-repl-node2:6379 -timeout 120s -wait-retry-interval 5s
      && redis-cli -h demo-redis-sentinel-repl-node2 slaveof ${varHostIp} 6379
      && redis-cli -h demo-redis-sentinel-repl-node2 config rewrite
      && echo \"成功join slave\""
    environment:
      - TZ=Asia/Shanghai
    networks:
      - net
    depends_on:
      - demo-redis-sentinel-repl-node1

  demo-redis-sentinel-repl-node3:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: demo-redis-sentinel-repl-node3
    image: my-redis:5.0.14
    command: redis-server /usr/local/etc/redis/redis.conf --port 6379 --replica-announce-ip ${varHostIp} --replica-announce-port 6381
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6381:6379
    networks:
      - net
    depends_on:
      - demo-redis-sentinel-repl-node1
  demo-redis-sentinel-repl-node3-slave-join:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: demo-redis-sentinel-repl-node3-slave-join
    image: my-redis:5.0.14
    command: sh -c "dockerize -wait tcp://demo-redis-sentinel-repl-node1:6379 -timeout 120s -wait-retry-interval 5s
      && dockerize -wait tcp://demo-redis-sentinel-repl-node3:6379 -timeout 120s -wait-retry-interval 5s
      && redis-cli -h demo-redis-sentinel-repl-node3 slaveof ${varHostIp} 6379
      && redis-cli -h demo-redis-sentinel-repl-node3 config rewrite
      && echo \"成功join slave\""
    environment:
      - TZ=Asia/Shanghai
    networks:
      - net
    depends_on:
      - demo-redis-sentinel-repl-node1