version: "3.0"

networks:
  net:
    name: demo-jenkins-net

services:
  demo-jenkins-server:
    build:
      context: ./
    container_name: demo-jenkins-server
    image: demo-jenkins-server-image
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - TZ=Asia/Shanghai
    networks:
      - net

