version: "3.0"

networks:
  net:
    name: demo-jenkins-net

services:
  demo-jenkins-server:
    container_name: demo-jenkins-server
    # NOTE: 很多插件已经不支持此版本
    # image: jenkins/jenkins:2.221-centos
    # NOTE: 这是新版本UI并且agent兼容jdk8
    image: jenkins/jenkins:2.346.3
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - TZ=Asia/Shanghai
    networks:
      - net

