version: "3.0"

# 创建网络
networks:
  net:
    name: demo-redis-mysql-cache-inconsistency-problem-net

services:
  # 启动mariadb
  demo-redis-mysql-cache-inconsistency-problem-db:
    container_name: demo-redis-mysql-cache-inconsistency-problem-db
    image: docker.118899.net:10001/yyd-public/demo-redis-mysql-cache-inconsistency-problem-db
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --skip-character-set-client-handshake
    ports:
      - 3306:3306
    networks:
      - net

  demo-redis-mysql-cache-inconsistency-problem-redis-server:
    container_name: demo-redis-mysql-cache-inconsistency-problem-redis-server
    image: redis:5.0.14
    # 设置redis密码
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass 123456
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6379:6379
    networks:
      - net