FROM mariadb:10.4.19

ENV LANG=C.UTF-8
ENV TZ=Asia/Shanghai

RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y unzip
# 需要安装less组件，否则aws s3api put-object命令会报告错误
RUN apt-get install -y less
# 定时备份数据cron
RUN apt-get install -y cron

# ENV DOCKERIZE_VERSION v0.6.1
# RUN curl --silent --output dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz https://bucketxyh.oss-cn-hongkong.aliyuncs.com/docker/dockerize-linux-amd64-v0.6.1.tar.gz
# RUN tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

# COPY db.sql /docker-entrypoint-initdb.d/
# COPY my-customize.cnf /etc/mysql/conf.d/my-customize.cnf

WORKDIR /data/auto-backup/

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
RUN cd /tmp/ && unzip awscliv2.zip
RUN cd /tmp/ && ./aws/install -i /usr/local/aws-cli -b /usr/bin

COPY auto-backup.sh /data/auto-backup/auto-backup.sh
RUN chmod 777 /data/auto-backup/auto-backup.sh

COPY db-auto-backup-cron /etc/cron.d/db-auto-backup-cron
RUN chmod 0644 /etc/cron.d/db-auto-backup-cron
RUN crontab /etc/cron.d/db-auto-backup-cron

# ENTRYPOINT [ "/bin/sh", "-c", "chmod 700 /data/auto-backup/auto-backup.sh && sleep 3600"]
ENTRYPOINT ["sh", "-c", "printenv > /etc/environment && cron -f"]
