version: "3.0"

services:
  demo-maven-compiler:
    container_name: demo-maven-compiler
    image: maven:3.3-jdk-8
    command: sh -c "rm -rf /usr/src/mytarget/* && mvn clean package && cp target/*.jar ../mytarget/ && mvn clean && rm -f /usr/src/mymaven/dependency*pom.xml"
    working_dir: /usr/src/mymaven
    volumes:
      - ./.m2:/root/.m2
      - ../:/usr/src/mymaven
      - ./mytarget:/usr/src/mytarget
    environment:
      - TZ=Asia/Shanghai