version: "3.0"

# 创建网络
networks:
  net:
    name: demo-redis-server

services:
  demo-redis-cluster-node1:
    container_name: demo-redis-cluster-node1
    image: redis:5.0.14
    # 必须设置cluster-announce-ip才能够在创建集群时节点join到master，否则会一直waiting...
    command: redis-server /usr/local/etc/redis/redis.conf --port 6380 --cluster-announce-ip ${varHostIp}
    volumes:
      - ./redis.cluster.conf:/usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6380:6380
      # 必须映射cluster-announce-bus-port才能够在创建集群时节点join到master，否则会一直waiting...
      - 16380:16380
    networks:
      - net

  demo-redis-cluster-node2:
    container_name: demo-redis-cluster-node2
    image: redis:5.0.14
    command: redis-server /usr/local/etc/redis/redis.conf --port 6381 --cluster-announce-ip ${varHostIp}
    volumes:
      - ./redis.cluster.conf:/usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6381:6381
      - 16381:16381
    networks:
      - net

  demo-redis-cluster-node3:
    container_name: demo-redis-cluster-node3
    image: redis:5.0.14
    command: redis-server /usr/local/etc/redis/redis.conf --port 6382 --cluster-announce-ip ${varHostIp}
    volumes:
      - ./redis.cluster.conf:/usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6382:6382
      - 16382:16382
    networks:
      - net

  redis-cluster-creator:
    image: redis:5.0.14
    entrypoint: [/bin/sh,-c,'echo "yes" | redis-cli --cluster create ${varHostIp}:6380 ${varHostIp}:6381 ${varHostIp}:6382']
    networks:
      - net
    depends_on:
      - demo-redis-cluster-node1
      - demo-redis-cluster-node2
      - demo-redis-cluster-node3

