version: "3.0"

services:
  db:
    image: mariadb:10.4.19
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --skip-character-set-client-handshake
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2.4
    # 设置redis密码
    command: redis-server --requirepass 123456
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "6379:6379"
