server.port=8080

spring.application.name=service-gateway
eureka.client.serviceUrl.defaultZone=http://localhost:8090/eureka/

# 路由规则
spring.cloud.gateway.routes[0].id=router-service-helloworld
spring.cloud.gateway.routes[0].uri=lb://service-helloworld
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/**

spring.cloud.gateway.routes[1].id=router-service-helloworld-oss-getObject
spring.cloud.gateway.routes[1].uri=lb://service-helloworld
spring.cloud.gateway.routes[1].predicates[0]=Path=/obs-*/**
spring.cloud.gateway.routes[1].filters[0]=ForwardedFilter
spring.cloud.gateway.routes[1].filters[1]=AddRequestHeader=header1,hvalue1
spring.cloud.gateway.routes[1].filters[2]=AddRequestParameter=param1,pvalue1

#spring.cloud.gateway.routes[2].id=router-service-helloworld-testResponseWithHttp400
#spring.cloud.gateway.routes[2].uri=lb://service-helloworld
#spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/testResponseWithHttp400
#spring.cloud.gateway.routes[2].filters[0]=TestResponseWithHttp400Filter

## 动态路由
## 表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务。
## 请求地址：http://localhost:8080/service-helloworld/api/v1/sayHello?name=%E4%BD%A0%E5%A5%BD
## 自动转发到：http://service-helloworld/api/v1/sayHello?name=%E4%BD%A0%E5%A5%BD
#spring.cloud.gateway.discovery.locator.enabled=true
## 是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了），比如以/service-helloworld/*的请求路径被路由转发到服务名为service-helloworld的服务上。
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

logging.level.root=info
logging.level.com.future.demo=debug