version: "3.0"

services:
  demo-openresty-https:
    container_name: demo-openresty-https
    image: openresty/openresty
    volumes:
     - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 80:80
