FROM docker.elastic.co/elasticsearch/elasticsearch:8.15.0

# 在线安装ik分词器
# https://github.com/medcl/elasticsearch-analysis-ik
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch https://release.infinilabs.com/analysis-ik/stable/elasticsearch-analysis-ik-8.15.0.zip

# 安装拼音插件
# https://github.com/medcl/elasticsearch-analysis-pinyin
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch https://release.infinilabs.com/analysis-pinyin/stable/elasticsearch-analysis-pinyin-8.15.0.zip
