server.port=8080

spring.application.name=service-gateway
eureka.client.serviceUrl.defaultZone=http://localhost:8090/eureka/

spring.cloud.gateway.routes[0].id=adminTest
spring.cloud.gateway.routes[0].uri=lb://service-provider
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/admin/**

spring.cloud.gateway.routes[1].id=nuserTest
spring.cloud.gateway.routes[1].uri=lb://service-provider
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/nuser/**

logging.level.root=info
logging.level.com.future.demo=debug