server.port=8101

spring.application.name=demo-springcloud-helloworld

# nacos\u6CE8\u518C\u4E2D\u5FC3\u914D\u7F6E
spring.cloud.nacos.discovery.server-addr=localhost:8848
management.endpoints.web.exposure.include=*

# sentinel\u914D\u7F6E
spring.cloud.sentinel.transport.dashboard=localhost:8858

spring.profiles.active=dev
